### ISSUE TITLE
How to not retain route paths for subdomains?

### ISSUE THREAD

**Issue by zilions** [patmood/wildcard-subdomains#8] opened 2017-03-01 11:21 UTC
I'm using your fantastic module within my application so that users can have their own subdomain for their profiles.

Take for example the following two dynamic subdomains:

```
bob.mydomain.com
jane.mydomain.com
```

These subdomains are not loading static content (JS/CSS/images) from my public folder that I specify via:

`app.use(express.static(process.env.PWD + '/public'));`

They also do not follow the correct paths for my API routes that I have setup.
Since as you stated, they will go to `/_sub/bob/api/` instead of `/api`.

My questions is, how can I choose to not retain paths so that all of my current API route calls and static calls (CSS/JS/images) still remain intact?

**Comment by patmood** [comment] 2017-03-03 04:21
Thank's for comment! It's a small module and I love seeing people using it :)

I think what you're describing is expected behavior, since those pages are on a separate domain. It should be fixed by using absolute paths for your images and api requests, for example `http://www.mydomain.com/api/users` instead of `/api/users`.

This is standard practice when you're front end is on a different domain - for example if your site is o one domain, your static content on a CDN with a different domain, and use an API from another service.

Hope that helps!

**Closed as completed** 2017-04-02 00:22 UTC
